INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Stacy","Contreras","neque@Sed.com"),
("Slavoj","Zizek","Nullam@facilisisloremtristique.net"),
("Eden","Nolan","Phasellus.elit.pede@gravidamolestie.com"),
("Portia","Ewing","arcu.Curabitur@nonsollicitudin.com"),
("Darrel","Oconnor","Donec.at@Proin.net"),
("Benjamin","Mooney","nisi@risusNunc.edu"),
("Evan","Ellison","eget.dictum.placerat@egestasrhoncus.co.uk"),
("Adam","Ewing","Aliquam.erat.volutpat@consectetueripsumnunc.edu"),
("Hilel","Rasmussen","nisi.nibh@DonecestNunc.edu"),
("Jayme","Nielsen","magna.malesuada.vel@Maecenas.net");
INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Kaden","Hunter","justo.Praesent@pharetraQuisqueac.org"),
("Rina","Park","enim@euultrices.co.uk"),
("Melissa","Vazquez","lobortis.quis.pede@musDonec.edu"),
("Margaret","Sanford","nibh@loremvitae.ca"),
("Charde","Decker","rutrum.justo@augueut.com"),
("Moses","Vincent","Nunc.ut@apurusDuis.net"),
("Keith","Hayes","sed.dolor.Fusce@dolor.edu"),
("Xander","Rodriguez","Proin.vel.arcu@egetmassa.net"),
("Thomas","Britt","Vivamus.non@anunc.com"),
("Conan","Shepherd","In.nec@elit.org");
INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Kasper","Thornton","orci@interdum.co.uk"),
("Barry","Curry","Quisque.libero.lacus@nectempusmauris.edu"),
("Cole","Logan","dis.parturient.montes@atsem.com"),
("Lisandra","Miranda","elementum@ettristique.org"),
("Bianca","Obrien","Sed.molestie@commodo.org"),
("George","Mcfadden","bibendum@purusDuiselementum.org"),
("Jade","Salinas","mauris.Morbi@dapibusligula.ca"),
("Sara","Orr","magna.et@necorciDonec.co.uk"),
("Dominic","Roberts","dolor@euismodin.com"),
("Christen","Marquez","elementum.sem.vitae@tempor.com");
INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Beverly","Diaz","consequat@liberolacus.com"),
("Zena","Evans","malesuada.fames@urnaNullam.ca"),
("Philip","Rivers","magnis@veliteu.org"),
("Benjamin","Harrison","tellus.Nunc@ante.edu"),
("Carla","Kirkland","ante@mipedenonummy.edu"),
("Ann","Hurst","a.enim.Suspendisse@tincidunt.edu"),
("Cyrus","Watson","nisl.sem.consequat@magnaPraesent.org"),
("Kelly","Norton","magna.Ut@urnaUt.org"),
("Florence","Jordan","fringilla.ornare.placerat@natoquepenatibus.net"),
("Odette","Humphrey","nascetur@Donec.edu");
INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Avye","Randall","gravida.Aliquam@mauriserateget.org"),
("Serena","Benjamin","et.magnis.dis@luctus.ca"),
("Finn","Randolph","justo.sit.amet@parturientmontesnascetur.edu"),
("Kirk","Weiss","aliquet@at.ca"),
("Christian","Newman","nibh@blanditviverra.edu"),
("Blossom","Vaughan","nisl@ligulaAenean.net"),
("Hilary","Shaw","sed@interdumSedauctor.ca"),
("Reuben","Cain","pharetra.Nam@idmollis.edu"),
("Kane","Travis","Curabitur.ut.odio@lacus.net"),
("Noah","Juarez","habitant.morbi@eleifendnecmalesuada.co.uk");
INSERT INTO `Teacher` (`FName`,`LName`,`EMail`) VALUES ("Herrod","Patterson","est.congue@interdum.com"),
("Timon","Nicholson","ut@euduiCum.org"),
("Fulton","Faulkner","pharetra.felis.eget@velit.org"),
("Eugenia","Anthony","fermentum@malesuada.co.uk"),
("Chandler","Lindsey","amet.metus.Aliquam@Maecenas.co.uk"),
("Kylee","Burks","penatibus@vitaerisus.net"),
("Juliet","Coleman","nunc@sempercursusInteger.com"),
("Ishmael","Roberts","dis.parturient@Utsagittislobortis.co.uk"),
("Zeph","Mcclure","Curabitur.consequat.lectus@variusNamport.co.uk");