INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("libero. Morbi","ullamcorper, nisl arcu iaculis enim, sit amet ornare","nndojzycj.wdn",11),
("Integer vitae","Proin nisl sem, consequat nec,","vhaudxgqn.fot",24),
("arcu. Vestibulum ut eros","eget, volutpat ornare, facilisis eget, ipsum. Donec","gbnkrnche.xkw",13),
("ac sem ut dolor","dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum","qusjvhjjt.pgs",21),
("aliquam adipiscing lacus. Ut","dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer","rlmtjejig.yra",20),
("Suspendisse aliquet molestie tellus.","eget, dictum placerat, augue. Sed molestie. Sed","njsfgwghi.two",26),
("pede,","et magnis dis parturient montes, nascetur ridiculus","qszrkymqd.lpv",15),
("tellus. Suspendisse","Mauris ut quam vel sapien imperdiet","aaxffsbyx.wfj",30),
("lobortis tellus","Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae,","rouqoxkqy.uny",30),
("enim, sit amet","eu, placerat eget, venenatis a, magna. Lorem ipsum dolor","hrbrdccfh.bpy",28);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("Vestibulum","erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.","xmpzawvcw.fzd",29),
("vulputate eu, odio.","erat, eget tincidunt dui augue eu tellus. Phasellus","nimiwctia.ube",21),
("lorem,","ultricies adipiscing, enim mi tempor lorem, eget mollis lectus","fokmnukun.qhw",23),
("ornare sagittis felis.","euismod est arcu ac orci. Ut","dicfceuum.rsq",20),
("sem","Mauris ut quam vel","nqawuygyt.got",19),
("sit amet","porta elit, a feugiat tellus lorem","jhmfjenct.qlw",15),
("euismod urna.","bibendum ullamcorper. Duis cursus, diam at pretium","lxojcccfi.aqb",9),
("feugiat. Sed nec metus","non lorem vitae odio sagittis semper. Nam","sbopgtrjd.dxh",9),
("Duis a mi fringilla","enim. Sed nulla ante,","kuwtiljvk.qmc",8),
("interdum ligula eu enim.","eros. Proin ultrices. Duis volutpat nunc","bedqdsguk.fri",10);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("vitae mauris","mus. Aenean eget magna. Suspendisse tristique neque","tqyxnjcsa.ard",17),
("a purus.","velit. Cras lorem lorem, luctus","ljbllhqez.jje",17),
("tempus risus. Donec","sed libero. Proin sed turpis nec mauris","litspvkpu.ynx",26),
("Vivamus non","Mauris molestie pharetra nibh. Aliquam","dwojahufb.tya",26),
("commodo","ultrices iaculis odio. Nam interdum enim non","fbyuwzmjz.kgc",23),
("ut nisi","et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat","qndqhywts.kid",5),
("Ut semper pretium","neque pellentesque massa lobortis","ssrrwmlpk.khx",5),
("enim. Etiam imperdiet dictum","ornare, elit elit fermentum risus,","cnypgqvau.urq",23),
("quis, tristique ac,","amet, consectetuer adipiscing elit. Aliquam","kvkqauvme.xyk",25),
("Sed id","ut cursus luctus, ipsum leo elementum sem, vitae","oquijzrqo.wyh",26);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("Aenean massa.","neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede","knonhaldr.wqs",14),
("Suspendisse eleifend. Cras sed","fermentum fermentum arcu. Vestibulum ante ipsum primis","sgbcnodeg.eee",24),
("amet risus. Donec egestas.","congue turpis. In condimentum. Donec at","xetndumtd.xpp",10),
("vel, convallis","at pretium aliquet, metus","rnvjigeey.hlf",3),
("metus.","montes, nascetur ridiculus mus. Proin vel arcu eu","dqnjhmugw.bhv",3),
("id","Phasellus libero mauris, aliquam eu,","qtskorcla.llj",8),
("eget odio. Aliquam vulputate","in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan","worjoxhue.vbx",16),
("tempus mauris erat","ante, iaculis nec, eleifend non, dapibus","wotttoebi.eos",8),
("et pede. Nunc sed","turpis nec mauris blandit mattis.","yzfgywrig.seo",27),
("erat neque non quam.","magna. Phasellus dolor elit, pellentesque a,","slvwqhdwe.ydr",22);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("eu","nisl. Maecenas malesuada fringilla est.","alhjpmsfj.jpa",21),
("neque. In ornare sagittis","vulputate, posuere vulputate, lacus. Cras","ypvfrikpp.jqm",8),
("nunc","Fusce aliquet magna a neque.","ttrsvkbaa.vey",28),
("cursus et,","scelerisque scelerisque dui. Suspendisse ac metus vitae","ekjoonaxc.sqq",8),
("faucibus","Nunc mauris elit, dictum eu, eleifend nec, malesuada ut,","hjlthicft.uvm",11),
("lorem fringilla","consequat purus. Maecenas libero est, congue a, aliquet vel,","nhepqywgi.azq",21),
("vitae purus gravida sagittis.","sed turpis nec mauris blandit mattis. Cras","cgpdrzcos.xru",10),
("eu odio tristique pharetra.","augue ac ipsum. Phasellus vitae mauris sit amet lorem","hjcdszyve.cyh",14),
("Phasellus elit pede, malesuada","neque. Nullam ut nisi","cvejdsirr.zjp",25),
("Mauris eu turpis. Nulla","non, hendrerit id, ante. Nunc mauris sapien,","aaeoshkso.frq",15);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("facilisis eget, ipsum.","scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada","itcqhvmdm.fyz",10),
("sociis natoque penatibus","natoque penatibus et magnis dis parturient montes, nascetur","wwwwyuhts.ymy",17),
("ultrices, mauris","vitae purus gravida sagittis. Duis gravida. Praesent","nicoqpmxr.kuj",14),
("a, auctor","rhoncus. Donec est. Nunc ullamcorper, velit in aliquet","mdezxwety.ocs",5),
("amet orci. Ut","sem molestie sodales. Mauris blandit enim","gatiiophq.rci",9),
("metus.","sem ut dolor dapibus gravida. Aliquam","ffznbsray.qas",23),
("Aenean massa. Integer","dictum mi, ac mattis velit justo nec ante. Maecenas mi","umutmmtdt.nqc",13),
("cursus in, hendrerit consectetuer,","eleifend nec, malesuada ut,","yuaneywbe.kyh",20),
("Ut nec urna","sed libero. Proin sed turpis","gxbefnrfx.sly",25),
("egestas nunc sed","ipsum ac mi eleifend egestas. Sed pharetra, felis","wraqkualb.pek",20);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("vel, faucibus","dolor egestas rhoncus. Proin nisl sem,","lwhzngcak.peo",1),
("Etiam laoreet,","Duis gravida. Praesent eu","zuqpgeqid.cqp",10),
("gravida nunc","ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo","xpdwwrnog.fom",21),
("odio a","Sed nunc est, mollis non, cursus non, egestas a, dui.","fitmngsqy.ttb",9),
("Ut","Nunc lectus pede, ultrices","mxvlhiiqu.xsn",6),
("ipsum leo elementum","Cras sed leo. Cras vehicula aliquet","gwwcoqdzm.tld",8),
("Mauris","luctus. Curabitur egestas nunc","lotjrspuh.xic",28),
("auctor,","dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris,","izngbvupy.tio",23),
("nec, leo.","Curae; Phasellus ornare. Fusce mollis.","tswpzrjfw.cbn",13),
("libero est, congue","Integer vitae nibh. Donec est mauris, rhoncus id, mollis","fvnrnxsov.owh",11);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("Nullam lobortis quam a","a neque. Nullam ut nisi a","vrmbncxck.ecd",7),
("Donec vitae","luctus ut, pellentesque eget, dictum placerat,","dyvlnjgmw.mdd",22),
("erat. Vivamus nisi.","Sed pharetra, felis eget varius ultrices, mauris","kjxznyfiw.xwu",27),
("hendrerit","mauris. Suspendisse aliquet molestie","yifzuotdy.ahg",25),
("Donec tempor, est","quis accumsan convallis, ante","gpvkpdmtp.bth",7),
("sed libero.","at pede. Cras vulputate","xkcyvbudu.ikz",25),
("magna. Nam ligula elit,","feugiat metus sit amet","nhjmtcsoo.otq",22),
("libero at auctor ullamcorper,","malesuada fames ac turpis egestas. Aliquam fringilla","tlngfgwvo.fph",23),
("risus varius orci, in","mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis","rqeaxeimu.jyv",17),
("id magna","dis parturient montes, nascetur ridiculus","zuwvrfxtc.fvy",3);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("eu sem.","arcu. Vestibulum ante ipsum primis in faucibus orci luctus","icsomhtob.umo",23),
("ligula. Donec luctus","ligula. Aenean euismod mauris eu","oojwwqbvt.pbv",30),
("adipiscing lacus.","a, auctor non, feugiat nec,","owxsjhtcw.bgv",10),
("in sodales elit","Quisque fringilla euismod enim.","ohxxhpgyr.afl",1),
("eu enim. Etiam","aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet","fuztkqnjq.vlj",30),
("aliquam","est arcu ac orci. Ut semper pretium neque. Morbi quis","lmptxnjoa.aun",20),
("amet","sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque","riyrbptth.awv",12),
("a ultricies adipiscing,","Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla","rjfxkalva.wic",19),
("lorem, eget mollis lectus","faucibus id, libero. Donec consectetuer mauris id sapien. Cras","mtcyftwnq.kkh",3),
("nec,","Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus.","uagyeyuwi.bka",2);
INSERT INTO `Material` (`Name`,`Description`,`FileURL`,`CourseID`) VALUES ("auctor non, feugiat nec,","parturient montes, nascetur ridiculus mus. Proin","rimhfkcua.zrc",4),
("mauris. Morbi non sapien","natoque penatibus et magnis dis parturient montes, nascetur ridiculus","akflxfjbb.hjl",28),
("In tincidunt congue","pharetra, felis eget varius ultrices, mauris ipsum porta elit, a","ghirkkioy.zvx",30),
("mi, ac mattis velit","et, rutrum non, hendrerit id, ante. Nunc mauris sapien,","evjdnntpy.ubt",20),
("non quam. Pellentesque","neque. Morbi quis urna.","enhdvuzpa.vml",26),
("laoreet, libero et tristique","mauris sit amet lorem","hohdszvee.alp",18),
("elementum, dui","Donec non justo. Proin","cjbnuasba.mvg",14),
("eget laoreet posuere, enim","varius et, euismod et, commodo at, libero. Morbi","azrodjkgr.pxl",6),
("Quisque ornare","pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer","dsbikqfda.pyt",28),
("Integer id magna","libero lacus, varius et, euismod et, commodo at, libero. Morbi","zigubnres.pgp",1);