INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Molly","Donovan","varius.ultrices@pretium.com","AAGA1548"),
("Naida","Sheppard","Aliquam@maurisutmi.co.uk","VDNS2829"),
("Ariel","Villarreal","urna.nec.luctus@nullaIntegerurna.edu","OQUA5183"),
("Veronica","Raymond","feugiat.tellus.lorem@lectusCum.org","XHNV5770"),
("Kennan","Puckett","lacinia@elementumdui.net","VPKD5093"),
("Jaden","Chapman","ut.aliquam.iaculis@dolor.edu","VYPB7743"),
("Oprah","Trevino","diam.Proin@atlacusQuisque.co.uk","OTXN5929"),
("Hannah","Middleton","et@Suspendissealiquet.net","GBGH0355"),
("Justine","Buckley","ligula@Donecfeugiat.ca","HQVL3388"),
("Minerva","Newman","id@nuncnulla.ca","XNZP7737");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Ralph","Miranda","enim.nisl.elementum@lacusCras.org","OQBG2963"),
("Maxwell","Reyes","sem.consequat@purusin.edu","CWJR0680"),
("Phyllis","Harrington","Aenean.euismod@turpisegestasAliquam.com","XZMH3754"),
("Addison","Patton","feugiat@pharetra.edu","PRDH6848"),
("Tanner","Conway","magna@ami.org","EEVP9880"),
("Macy","Cote","luctus.felis@commodo.net","PKVQ1841"),
("Hedwig","Banks","Donec@Crasegetnisi.co.uk","ORZC7265"),
("Brock","Robbins","convallis.dolor@odioPhasellusat.org","JZBJ5507"),
("Aline","Bolton","euismod@odio.org","CORT6622"),
("Scarlet","Hammond","Duis.elementum.dui@magna.ca","BUSS9888");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Moses","Nguyen","est.Nunc.ullamcorper@purus.net","SMDJ7445"),
("Yardley","Elliott","lectus@etrutrum.edu","OJQN3825"),
("Caryn","Chen","leo.Cras@sedconsequatauctor.edu","FPYY2248"),
("Bernard","Hooper","massa@lectus.net","AFPD7985"),
("Rhea","Maynard","accumsan@lacusQuisque.co.uk","EZDK1741"),
("Peter","Holland","euismod.ac.fermentum@tortorNunc.co.uk","HFWO6285"),
("Chandler","Tate","aliquet@NullamenimSed.edu","GWPY1459"),
("Aristotle","Lloyd","mi.tempor.lorem@magna.org","CXEE5914"),
("Dara","Hunter","fermentum.vel@scelerisque.ca","GXAC8288"),
("Valentine","Lewis","enim.mi.tempor@urnaVivamus.net","AIYB9857");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Lawrence","Richard","rhoncus.Donec@venenatis.net","MJTT0675"),
("Donovan","Talley","Vestibulum@dis.co.uk","SQLA6657"),
("Octavia","Herman","tellus.sem.mollis@eu.edu","YIJM5987"),
("Kermit","Puckett","mi@vitaesodalesat.ca","GYWA9223"),
("Cara","Haney","Praesent.interdum.ligula@eleifend.co.uk","RSSK8107"),
("Thor","Chan","tristique.pellentesque.tellus@sit.com","DHDG2069"),
("Adria","Mccall","Sed.eu.eros@mollisneccursus.org","EBCN0716"),
("Leandra","Blake","consectetuer.cursus.et@convallisdolorQuisque.edu","MLDM6662"),
("Hyacinth","Conway","dis@magnaSed.edu","MDLG6611"),
("Tamekah","Reid","mi@Praesenteunulla.ca","CXIM3483");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Lara","French","in@anteipsum.net","IBPU3945"),
("Judah","Dennis","nostra.per@duisemper.net","NCRH0719"),
("Nelle","Kidd","volutpat.Nulla.dignissim@aliquetmagnaa.ca","ISEC5635"),
("Fitzgerald","Weaver","et@Nunccommodo.org","MCXO9909"),
("Beatrice","Ryan","est.mollis@aliquamadipiscing.com","SZTS3928"),
("Kylee","Brown","Quisque.fringilla.euismod@nislarcuiaculis.org","DWXA2133"),
("Amelia","Downs","magna.Lorem.ipsum@nectellus.net","QQEU0622"),
("Hilel","Bartlett","sodales.purus@ipsumdolorsit.ca","LEZE0126"),
("Demetria","Hunt","rutrum.eu.ultrices@Sedetlibero.org","FPXE6162"),
("Macey","Bowen","Quisque.ornare.tortor@volutpat.co.uk","PXVE3213");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Sade","Barlow","non@inmolestie.edu","TNIX9177"),
("Savannah","Doyle","aliquet.nec.imperdiet@venenatislacus.net","GQYN9368"),
("Maxine","James","eu.euismod.ac@Sednulla.org","HNHC2375"),
("Hedley","Lott","ante.dictum.mi@Aliquamnec.co.uk","VBBU8556"),
("Yvette","Stanton","enim@Curabiturdictum.ca","BBGZ1333"),
("Lucian","Castaneda","elit.pretium@orci.co.uk","EXTK7287"),
("Galena","Farmer","Suspendisse.eleifend.Cras@ipsumnonarcu.edu","HIOO0750"),
("Lane","Wolfe","nunc.Quisque.ornare@urna.co.uk","DVCH3307"),
("Rajah","Johnston","auctor.nunc.nulla@Aliquam.org","TZAH6223"),
("Hammett","Avila","Pellentesque.tincidunt.tempus@Nunc.net","QIEL8261");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Evan","Henson","libero@diamvelarcu.net","ELLI1464"),
("Jenette","Mccarty","nonummy.Fusce.fermentum@auctor.ca","UYEY9572"),
("Eden","Lang","Donec.vitae.erat@lectus.ca","TCRL6171"),
("Igor","Hunt","tellus.non.magna@vitae.edu","WLKU0114"),
("George","Horne","placerat@Lorem.co.uk","JZIX7688"),
("Lael","Sexton","lectus.ante.dictum@dolor.com","DEGI9513"),
("Steel","Moses","consectetuer.ipsum.nunc@dolor.co.uk","JACW5687"),
("Xena","Moran","tristique.pharetra.Quisque@tortorIntegeraliquam.co.uk","IVKX8967"),
("Valentine","Reynolds","Donec.feugiat.metus@tempus.org","IBVC0337"),
("Amethyst","Marsh","Integer.vitae@imperdietnon.com","NJWM6080");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Keith","Moreno","magna.Ut@Phasellusinfelis.ca","UMBI7818"),
("Hunter","Duncan","cursus@odio.co.uk","MUJH9543"),
("Moses","Beck","Nunc@tempuseuligula.com","BNWI9614"),
("Mollie","Mayer","turpis@aenimSuspendisse.edu","RSBC6758"),
("Louis","Park","nunc@elitCurabitur.net","VCSP0409"),
("Zelda","Dixon","lorem.semper.auctor@acmattisvelit.edu","SUOT5828"),
("Vincent","Irwin","lectus.convallis@dolor.com","ONHY6669"),
("Vladimir","Watts","Nulla@quamCurabitur.co.uk","JBCS9600"),
("Cadman","Tucker","mollis.lectus.pede@parturientmontes.com","PMUD2958"),
("Stuart","Barrett","auctor.Mauris@vitae.ca","UBRY7815");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Kenneth","Blevins","ipsum.leo@ultricessit.com","IQDG4729"),
("Asher","Burch","malesuada.vel@fringillami.ca","CELB7628"),
("Avram","Dunn","aliquet@Aliquamrutrumlorem.co.uk","AKXZ3928"),
("Tatyana","Garrett","per.conubia@pulvinararcuet.co.uk","QWAR7921"),
("Hope","Dorsey","eu.arcu@faucibuslectus.edu","APQU8209"),
("Colleen","Figueroa","lectus.a@ultriciesadipiscing.ca","KWAU9825"),
("Genevieve","Snow","non.vestibulum@eleifendegestas.ca","DNQY5295"),
("Alfonso","Pitts","mauris.sapien.cursus@necorci.com","CFHG0295"),
("Magee","Mcintyre","Proin.vel.arcu@euodio.edu","KWAH7592"),
("Xerxes","Richards","vitae.erat.vel@nislelementum.com","NPIG1017");
INSERT INTO `Student` (`FName`,`LName`,`EMail`,`Code`) VALUES ("Carl","Calderon","neque@Suspendisseac.net","BPJT5986"),
("Glenna","Ochoa","auctor.ullamcorper@accumsan.net","ACTF1906"),
("Virginia","Waller","parturient.montes@Namporttitor.ca","MQOM3107"),
("Ella","Saunders","arcu@nunc.co.uk","XPLS9433"),
("Wanda","Greer","feugiat@Duis.org","JNQH1374"),
("Bruce","Byers","vitae@at.edu","YZIO9147"),
("Jason","Arnold","nulla.Donec@ipsum.com","MWYZ3500"),
("Stephen","Sparks","Mauris.nulla@dolor.net","PIXA0889"),
("Quemby","Snider","scelerisque.sed@venenatisvel.org","CPXR0528"),
("Odette","Hamilton","a.purus@odioauctorvitae.ca","PZSA5152");
